### ISSUE TITLE
Error in Build!

### ISSUE THREAD

**Issue by QuestionPython** [furryfaust/lyca#1]
$ cd src
--------
$ ls
--------
```
codegen  lexer  lyca.go  parser
```

$ go build .
-----------
```
codegen/codegen.go:6:5: cannot find package "llvm.org/llvm/bindings/go/llvm" in any of:
	/usr/lib/go-1.8/src/llvm.org/llvm/bindings/go/llvm (from $GOROOT)
	/home/guest/go/src/llvm.org/llvm/bindings/go/llvm (from $GOPATH)
```
$ go get llvm.org/llvm/bindings/go/llvm
-------
```
package llvm.org/llvm/bindings/go/llvm: unrecognized import path "llvm.org/llvm/bindings/go/llvm" (parse https://llvm.org/llvm/bindings/go/llvm?go-get=1: no go-import meta tags ())
```

how fix?

**Comment by questionpython** [comment]
@furryfaust

**Comment by furryfaust** [comment]
Ah, sorry for the delayed reply. Needless to say, the error you are getting is from the lack of go bindings for llvm. To resolve that, you would need to:

1. `$ go get llvm.org/llvm/bindings/go/llvm`
2. `$ cd $GOPATH/src/llvm.org/llvm/bindings/go`
3. `$ ./build.sh`

This should be enough to install the go bindings for llvm. If you face any errors, check out the [README for the llvm go bindings](http://llvm.org/svn/llvm-project/llvm/trunk/bindings/go/README.txt).
